FROM php:8.4-fpm

# Instalar dependencias necesarias
RUN apt-get update && apt-get install -y \
    supervisor \
    cron \
    zip \
    unzip \
    git \
    libzip-dev \
    libfreetype6-dev \
    libjpeg-dev \
    libpng-dev \
    libgmp-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd zip gmp pdo pdo_mysql opcache \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Instalar Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Crear directorios de logs
RUN mkdir -p /var/log/nginx /var/log/supervisor /var/www/html/storage/logs

# Configurar cron
RUN echo "* * * * * cd /var/www/html && php artisan schedule:run >> /var/www/html/storage/logs/scheduler.log 2>&1" > /etc/cron.d/artisan-cron \
    && chmod 0644 /etc/cron.d/artisan-cron

# Copiar configuraciones
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./supervisor.conf /etc/supervisor/conf.d/supervisor.conf
COPY ./php/conf.d/opcache.ini /usr/local/etc/php/conf.d/opcache.ini
COPY ./php/conf.d/php.ini /usr/local/etc/php/conf.d/php.ini
COPY ./entrypoint.sh /entrypoint.sh

# Configurar permisos
RUN chown -R www-data:www-data /var/www/html/storage /var/log \
    && chmod +x /entrypoint.sh

# Exponer puertos
EXPOSE 80 9000

# Punto de entrada
ENTRYPOINT ["/entrypoint.sh"]